query Orgs (
  $id: Int
) {
  Orgs (
    id: $id
  ) {
    data {
      id
      name
      address
      city
      province
      phone
      promos {
        title
        photo_url
      }
    }
  }
}